export const PORTFOLIO_CHANGE_CATEGORY = "PORTFOLIO_CHANGE_CATEGORY";
export const PORTFOLIO_GET_CATEGORIES_SUCCESS = "PORTFOLIO_GET_CATEGORIES_SUCCESS";

export const PORTFOLIO_GET_ITEMS_SUCCESS = "PORTFOLIO_GET_ITEMS_SUCCESS"